name: Docker Workflow

on:
  - push
  
jobs: 
  docker_build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Build 
      run: docker build -t docker.io/jamesafful25/resume-app:latest .

    - name: Docker Login
      run: docker login --username=jamesafful25 --password=Mankind9042@

    - name: Docker Publish 
      run: docker push docker.io/jamesafful25/resume-app:latest

  docker_deploy:
    needs: docker_build
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Docker Login
        run: docker login --username=jamesafful25 --password=Mankind9042@
      - name: Docker Run
        run: docker run -d -p 8080:80 docker.io/jamesafful25/resume-app:latest