name: Docker Workflow

on:
 - push
    
jobs: 
  docker_build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Debugging Info
      run: |
        echo "Listing .github/workflows/resume-app/"
        ls -al .github/workflows/resume-app/

    - name: Docker Build 
      run: docker build -t resume-app:latest -f .github/workflows/resume-app/Dockerfile .

    - name: Docker Login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Store password as a secret
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username=jamesafful25 --password-stdin

    - name: Docker Publish 
      run: docker push docker.io/jamesafful25/resume-app:latest

  docker_deploy:
    needs: docker_build
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Store password as a secret
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username=jamesafful25 --password-stdin

      - name: Docker Run
        run: docker run -d -p 8080:80 docker.io/jamesafful25/resume-app:latest