name: Docker Workflow

on:
  push

jobs: 
  docker: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Build
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: jamesafful25
          DOCKER_PASSWORD: Mankind9042@
          IMAGE_NAME: resume-app
        run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

      - name: Docker Login
        env:
          DOCKER_USERNAME: jamesafful25
          DOCKER_PASSWORD: Mankind9042@
        run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

      - name: Docker Publish 
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: jamesafful25
          IMAGE_NAME: resume-app
        run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Run
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: jamesafful25
          DOCKER_PASSWORD: Mankind9042@
          IMAGE_NAME: resume-app
        run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
