on:
  push:
    branches:
      - main  # Adjust to your main branch name if different

jobs: 
  docker_build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Build 
        run: docker build -t jamesafful25/resume-app:latest -f .github/workflows/resume-app/Dockerfile .

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username="${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Publish 
        run: docker push jamesafful25/resume-app:latest

  docker_deploy:
    needs: docker_build
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username="${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Run
        run: docker run -d -p 8080:3000 jamesafful25/resume-app:latest
