name: Deploy Resume WebApp to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: prod
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: ${{ secrets.TARGET_DIR }}  # Ensure this points to the correct directory

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update and install apache2 if not already installed
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            
            # Change to the directory where your files are located
            cd /path/to/resume-app  # Adjust this to your actual directory path
            
            # Clear the previous contents of the web root
            sudo rm -rf /var/www/html/*
            
            # Move new files to the Apache web root
            sudo mv * /var/www/html/
            
            # Verify files have been moved correctly
            ls -l /var/www/html/
