name: Deploy to various Environments

on:
  push:
    branches:
      - main

jobs:
  deploy_dev:
    uses: jamesafful25/reusable-workflows/.github/workflows/deploy.yml@main
    with:
      environment: dev

  deploy_staging:
    needs: deploy_dev
    uses: jamesafful25/reusable-workflows/.github/workflows/deploy.yml@main
    with:
      environment: staging

  deploy_prod:
    needs: deploy_staging
    uses: jamesafful25/reusable-workflows/.github/workflows/deploy.yml@main
    with:
      environment: production
#*********


