name: Pipeline with Unit Testing

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS Version
        uses: actions/setup-node@v3
        with:
          node-version: 14  # or 16 if using Dart Sass

      - name: Install Build Tools
        run: sudo apt-get install -y build-essential

      - name: Clean npm Cache
        run: npm cache clean --force

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Unit Testing
        run: npm test
        
      - name: Archive Test Result
        uses: actions/upload-artifact@v3
        with:
          name: Mocha-Test-Result
          path: test-results.xml